# Generated by Django 2.2.7 on 2021-12-16 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CokeBottleUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=True)),
                ('app_installed', models.BooleanField(default=False)),
                ('user_info', models.TextField()),
                ('video_link', models.URLField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Short_Coke_Bottle_Users_Profile',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CurzeUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=True)),
                ('app_installed', models.BooleanField(default=False)),
                ('user_info', models.TextField()),
                ('video_link', models.URLField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Curze_Users_Profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='NadiaUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=True)),
                ('app_installed', models.BooleanField(default=False)),
                ('user_info', models.TextField()),
                ('video_link', models.URLField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Nadia_Users_Profile',
                'ordering': ('created',),
            },
        ),
    ]
