# Generated by Django 2.2.7 on 2021-12-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cokebottleuserprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Client_Profiles'},
        ),
        migrations.AlterModelOptions(
            name='curzeuserprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Client_Profiles'},
        ),
        migrations.AlterModelOptions(
            name='nadiauserprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Client_Profiles'},
        ),
    ]
