# Generated by Django 2.2.7 on 2021-12-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211216_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cokebottleuserprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='curzeuserprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='nadiauserprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Profiles'},
        ),
    ]
