# Generated by Django 2.2.7 on 2021-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211216_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cokebottleuserprofile',
            name='app_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curzeuserprofile',
            name='app_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nadiauserprofile',
            name='app_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
