# Generated by Django 2.2.7 on 2021-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211216_0317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurzeUserProfile',
        ),
        migrations.AddField(
            model_name='cokebottleuserprofile',
            name='link_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nadiauserprofile',
            name='link_visits',
            field=models.IntegerField(default=0),
        ),
    ]
