# Generated by Django 2.2.7 on 2021-12-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211217_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cokebottleuserprofile',
            name='redirect_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='nadiauserprofile',
            name='redirect_link',
            field=models.URLField(default=''),
        ),
    ]
