# Generated by Django 2.2.7 on 2021-12-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211228_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cokebottleuserprofile',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='nadiauserprofile',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='cokebottleuserprofile',
            name='id_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cokebottleuserprofile',
            name='video_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='nadiauserprofile',
            name='id_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='nadiauserprofile',
            name='video_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
