# Generated by Django 2.2.7 on 2021-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211228_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
