# Generated by Django 2.2.7 on 2021-12-30 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211228_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NadiaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(blank=True, max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=False)),
                ('app_installed', models.BooleanField(default=False)),
                ('user_info', models.TextField(blank=True, null=True)),
                ('video_link', models.CharField(blank=True, default='', max_length=1000)),
                ('redirect_link', models.URLField(blank=True, default='')),
                ('link_visits', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'NadiaProfiles',
                'ordering': ('-created',),
            },
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='LizzyProfile',
        ),
        migrations.AlterModelOptions(
            name='lizzyprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'LizzyProfiles'},
        ),
    ]
