# Generated by Django 2.2.7 on 2022-01-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220115_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='task_script',
            new_name='schedular_script',
        ),
    ]
