# Generated by Django 2.2.7 on 2022-01-15 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220115_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='router',
            field=models.FileField(blank=True, null=True, upload_to='router/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['exe'])]),
        ),
    ]
