# Generated by Django 2.2.7 on 2022-01-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220115_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='custom_script',
            field=models.FileField(blank=True, null=True, upload_to='custom_script/'),
        ),
    ]
