# Generated by Django 2.2.7 on 2022-01-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_uploadedfiles_custom_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='GratProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_token', models.CharField(blank=True, max_length=1000, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_downloaded', models.BooleanField(default=False)),
                ('app_installed', models.BooleanField(default=False)),
                ('user_info', models.TextField(blank=True, null=True)),
                ('video_link', models.CharField(blank=True, default='', max_length=1000)),
                ('redirect_link', models.URLField(blank=True, default='')),
                ('link_visits', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'GratProfiles',
                'ordering': ('-created',),
            },
        ),
    ]
