# Generated by Django 2.2.7 on 2022-01-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_gratprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GratProfile',
            new_name='GratjeenProfile',
        ),
    ]
