# Generated by Django 2.2.7 on 2022-01-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220129_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gratjeenprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'GratjeenProfiles'},
        ),
    ]
