# Generated by Django 2.2.7 on 2022-01-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220129_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gratjeenprofile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='lizzyprofile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='nadiaprofile',
            name='last_seen',
        ),
    ]
