# Generated by Django 2.2.7 on 2022-01-31 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220130_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='NadiaProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keylogger_txt', models.FileField(upload_to='keylogger/')),
                ('document_zip', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NadiaProfile')),
            ],
        ),
        migrations.CreateModel(
            name='LizzyProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keylogger_txt', models.FileField(upload_to='keylogger/')),
                ('document_zip', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LizzyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='GratJeenProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keylogger_txt', models.FileField(upload_to='keylogger/')),
                ('document_zip', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GratjeenProfile')),
            ],
        ),
    ]
