# Generated by Django 2.2.7 on 2022-03-22 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_gratjeenprofiledetails_lizzyprofiledetails_nadiaprofiledetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploadedfiles',
            new_name='DownloadedFiles',
        ),
        migrations.RemoveField(
            model_name='gratjeenprofiledetails',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lizzyprofiledetails',
            name='client',
        ),
        migrations.RemoveField(
            model_name='nadiaprofiledetails',
            name='client',
        ),
        migrations.DeleteModel(
            name='GratjeenProfile',
        ),
        migrations.DeleteModel(
            name='GratJeenProfileDetails',
        ),
        migrations.DeleteModel(
            name='LizzyProfileDetails',
        ),
        migrations.DeleteModel(
            name='NadiaProfileDetails',
        ),
    ]
