# Generated by Django 2.2.7 on 2022-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220322_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizzyprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nadiaprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
